Implement marvel api
erikdvt/marv-lous pull request #1
Opened 2022-03-24 12:16 UTC by erikdvt

Implemented Marvel API to print details about 100 comics.
Created config.xcconfig and added it to .gitignore to hide api key from repository. (not yet working, API Key in constants file.)
Removed comments.

2022-03-24 14:14 UTC, bgouws requested changes
Just a little bit of clean up -Nice PR man looking good!

2022-03-24 14:14 UTC, bgouws commented on Marv-Lous/Marv-Lous/Models/ComicDataWrapper.swift
> +    let code: Int?
If these come back from the service consistently you can remove the optional `?`

2022-03-24 14:14 UTC, bgouws commented on Marv-Lous/Marv-Lous/Models/ComicDataWrapper.swift
> +    let code: Int?
Also just a note so you know 😄 

If you don't need this all this information you don't necessarily need to decode it 👍

2022-03-24 14:14 UTC, bgouws commented on Marv-Lous/Marv-Lous/Controllers/ViewController.swift
>  class ViewController: UIViewController {
We can give this a more meaningful name 😄 please use the refactor tool so that it doesn't break your storyboard 😄 

Ask Kirsty if you need some help with this 👍

2022-03-24 14:14 UTC, bgouws commented on Marv-Lous/Marv-Lous/Controllers/ViewController.swift
> +                print(comicsArray.data!.results!.description)
Some force unwrapping here 😄 rather unwrap this safely.

2022-03-25 05:18 UTC, bgouws approved these changes
Looks good man 👍

2022-03-25 05:36 UTC, erikdvt commented on Marv-Lous/Marv-Lous/Models/ComicDataWrapper.swift
> +    let code: Int?
The documentation lists everything as optional, but at the very least it should return the wrapper and container of results so I removed those optionals.

I'll keep the information there for now and later remove what I find out what I don't need.

2022-03-25 05:37 UTC, erikdvt commented on Marv-Lous/Marv-Lous/Controllers/ViewController.swift
>  class ViewController: UIViewController {
I refactored the name to LandingPageViewController.

2022-03-25 05:38 UTC, erikdvt commented on Marv-Lous/Marv-Lous/Controllers/ViewController.swift
> +                print(comicsArray.data!.results!.description)
I made those non-optional so I no longer needed to force unwrap them.

2022-03-25 05:41 UTC, bgouws commented
Just let your peers know that they can also take a look at your PR - just a note for anyone reading this - this PR does not need to be in MVVM yet.

2022-03-25 06:21 UTC, simekanidvt approved these changes

2022-03-25 06:45 UTC, merged