Implement detail view page
erikdvt/marv-lous pull request #6
Opened 2022-04-22 06:58 UTC by erikdvt

**Detail view page:**

- Shows details about a single comic
- Has buy button which directs user to Marvel website in Safari to buy comic
- Add button - TODO
- Has auto-layout with scroll view for landscape
- Tab bars and navigation bar implemented as well

**Screenshots:**
![Simulator Screen Shot - iPhone 11 - 2022-04-22 at 08 36 02](https://user-images.githubusercontent.com/101548572/164620928-f0bb4a40-a740-427f-a793-0b4361416851.png)
![Simulator Screen Shot - iPhone 11 - 2022-04-22 at 08 36 13](https://user-images.githubusercontent.com/101548572/164620949-b270ddcf-6d5b-4abf-979c-585af0403a82.png)

2022-04-29 05:35 UTC, bgouws requested changes
Very nice PR -lets just handle that error 😄

2022-04-29 05:35 UTC, bgouws commented on Marv-Lous/Marv-Lous/Controllers/DetailsViewController.swift
> +        print(error)
Think we can handle this in this PR 😄

2022-05-03 20:03 UTC, bgouws approved these changes
Looks good 😄

2022-05-05 09:08 UTC, kirsty14 approved these changes
Looking good 👍🏻

2022-05-06 13:56 UTC, merged